name: moon_leaf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.2.0
  flutter_bloc: ^9.1.1
  go_router: ^16.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  modal_bottom_sheet: ^3.0.0
  bloc: ^9.0.0
  meta: ^1.16.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.7.0

flutter:
  uses-material-design: true
